### ISSUE TITLE
Right Click to Open a Door also places a block.

### ISSUE THREAD

**Issue by nmarshall23** [SoraZodia/Survival-Tweaks#1]
I'm not sure what other info you need, to reproduce this bug. When I Right Click to open a door holding a tool, the door opens and a block is placed. 

What should happen is that the door is opened, and no block is placed.

**Comment by SoraZodia** [comment]
I was able to reproduce it. Will let you know when it get fixed.

**Comment by SoraZodia** [comment]
Should be fixed now.
