### ISSUE TITLE
Mod interaction crash with Welcome to the Jungle.

### ISSUE THREAD

**Issue by tyra314** [SoraZodia/Survival-Tweaks#10]
There seems to be an issue with this mod and Welcome to the jungle.
https://gist.github.com/tyra314/9d1fda16f2a9008fd8f442eeb96a0b71

It happens, when you right click a Jungle brazier from Welcome to the Jungle.

Crossissue: https://minecraft.curseforge.com/projects/welcome-to-the-jungle?comment=35

**Comment by tyra314** [comment]
Might be related to #9

**Comment by SoraZodia** [comment]
It is, a patch should be up soon

**Comment by tyra314** [comment]
Can confirm, works now for me. Thank you.
