### ISSUE TITLE
Tool placing conflicts with offhand

### ISSUE THREAD

**Issue by tyra314** [SoraZodia/Survival-Tweaks#11]
In the 1.11.2 version, I'm usually have a torch in my offhand, so a right-click places one. However, that conflicts with your tool placing option. The torch gets placed and then overwritten with whatever happens to be next to my tool. Very strange behavior.

Also, I guess it has something to do with this interaction, you can override blocks. So I right-clicked at the ceiling and the stone got replaced with a dirt block.

**Comment by SoraZodia** [comment]
Well that's a interesting bug, I'll get that fixed by the time of the next release.

**Comment by SoraZodia** [comment]
It's fixed, next update will have that in.
