### ISSUE TITLE
crash issue with tough a nails

### ISSUE THREAD

**Issue by EchenCraft** [SoraZodia/Survival-Tweaks#12]
A crash occurs when holding a torch and right clicking on a campfire in tough as nails

can be replicated with only this mod and tough as nails

place a campfire, right click with torch. instacrash

posting this [here](https://github.com/Glitchfiend/ToughAsNails/issues/246) with tough as nails as well

**Comment by SoraZodia** [comment]
What version were you using? Because I'm sure I had fixed that already.

A crash report would be nice as well.

**Comment by EchenCraft** [comment]
Sorry Ill pop it again let me set it up and generate a report real quick

**Comment by EchenCraft** [comment]
https://pastebin.com/aD3KRN8Q

**Comment by EchenCraft** [comment]
I can pastebin this and the log if yould like but like I said its just both of those mods and forge 12.18.3.2281

**Comment by SoraZodia** [comment]
The latest version already has this fixed, although it's on another Minecraft version. I'll backport the fix so you can continue playing on your currect version, it should be up within the day.
