### ISSUE TITLE
Mod uses backslash for folders in Linux

### ISSUE THREAD

**Issue by creeper123123321** [SoraZodia/Survival-Tweaks#13]

**Comment by SoraZodia** [comment]
I think I know what you are talking about, but can you provide a screenshot of the problem just so I can get a better idea of what is happening?

**Comment by creeper123123321** [comment]
![image](https://user-images.githubusercontent.com/7974274/29487307-706c50e2-84cd-11e7-9ca1-504fcb392814.png)

**Comment by SoraZodia** [comment]
Should be fixed now
