### ISSUE TITLE
Hand waggling and placing items on tile entities when accessing them

### ISSUE THREAD

**Issue by Darkmega18** [SoraZodia/Survival-Tweaks#16]
What it says on the tin.

While rightclicking anything in midair you constantly "attack the air" with it. Or "waggle it around" as I called it. the block rightclicking with tools thing causes no sound (atleast on the server) when it places stuff.
Also when rightclicking with something placeable on an object that opens a gui, in my case, my transmutation tablet, but it'll probably happen with other things, the block I'm holding will be placed onto it while also accessing the gui as if I was holding shift.

Little buggy methinks. the issue stops when you turn off block placing with tools. But the waggling still persists afterwards.

**Comment by SoraZodia** [comment]
The waggling is something I put in cause I thought it would be nice if the player had an option to wave their fist around other than using left-clicks. I could add an option to disable that if you wish.

Tool block placing had always given me quite a bit of trouble but that shouldn't had happen in your case. Could you verify if it will also happen to other things like a chest, door, or furnace? What version of the mod are you on though?

**Comment by Darkmega18** [comment]
oh dang. I already removed it because I didn't seed the tweaks as super required and stuff. :V but it was 5.0.2 for 1.12.2. The waggling was a little off putting when I had blocks in my hands and was shifting off edges. cause sometimes it'd waggle when building, which made me think I placed the block and then I let go and went off the edge cause the block didn't actually place server side. :V

But now that you explain it, I do see the point now. but yeah, maybe a disabler for it would be alright. Since... I think a lot of people will probably use quark and thats got the emotes and stuff in it, right?

**Comment by SoraZodia** [comment]
That's fine, v5.0.3 is the latest version though. I'll add something in the config that will let players enable/disable the waggling. 

The sound not playing is probably something related to the server, cause it would works on singleplayer.

**Comment by SoraZodia** [comment]
The sounds and hand waggle (removed instead of adding a config option) should be fixed now in v5.0.4. I could not recreate the bug with the tool block placement, so I'm guessing it was a problem in v5.0.2 (your version) and was later fixed in v5.0.3.
