### ISSUE TITLE
Right click error with Thaumcraft

### ISSUE THREAD

**Issue by serialtasted** [SoraZodia/Survival-Tweaks#18]
Hey there,
It seems that there's an error that makes impossible to create the research table from Thaumcraft.

Already reported on Thaumcraft git also but thought it would be a good ideia for you to know too.

Here's the log on console:
> [01:26:47] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
> Caused by: java.lang.NullPointerException
> 	at thaumcraft.common.blocks.basic.BlockTable.func_180639_a(BlockTable.java:64) ~[BlockTable.class:?]
> 	at sorazodia.survival.mechanics.PlayerActionEvent.blockRightClick(PlayerActionEvent.java:124) ~[PlayerActionEvent.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_875_PlayerActionEvent_blockRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
> 	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) ~[ForgeHooks.class:?]
> 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) ~[lv.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
> 	... 5 more

**Comment by SoraZodia** [comment]
The bug should be fixed now, let me know if it's still there
