### ISSUE TITLE
[Suggestion] Disabling Tools Block Placing

### ISSUE THREAD

**Issue by Tsyklop** [SoraZodia/Survival-Tweaks#2]
Please add to disable this function in the configuration. and also could add the ability to disable all the features of fashion ...

toolsblockPlacing = false;
swordBlocking = true;

and so on..

**Comment by SoraZodia** [comment]
Makes sense, I'll add it in.

**Comment by Tsyklop** [comment]
@SoraZodia Thanks

**Comment by SoraZodia** [comment]
Added in v1.1.0
