### ISSUE TITLE
Crash - Right clicking with wooden axe on Rustic wild berry bush

### ISSUE THREAD

**Issue by DWX12** [SoraZodia/Survival-Tweaks#20]
Got a crash from right clicking a Rustic wild berry bush with a wooden axe:

https://paste.dimdev.org/anobakeyul.mccrash

Not sure if it's just a Rustic bush or if it's other things as well. Will report as I experience issues.

**Comment by SoraZodia** [comment]
Does it happens when you try any other tools? I'll see if I can find anything when I get the time.

**Comment by ghost** [comment]
Preface: install vanilla fix, it's great for telling you exactly what mod is causing an issue!

Ran into the same issue, although when trying to make a path with a shovel. the issue occurs when you have any placeable blocks on either side of the shovel (non-placeable blocks don't cause an issue).

https://paste.dimdev.org/loqihenula.mccrash

Edit: I think this is also causing issues with hoes (the farming tool, not the other one>.>)

**Comment by SoraZodia** [comment]
Should be fixed in v5.1.1. Let me know if it's still a problem. I should be able to fix it faster this time around >.>
