### ISSUE TITLE
[Enhancement] Burn entities in any dimension

### ISSUE THREAD

**Issue by ghost** [SoraZodia/Survival-Tweaks#21]
Would it be possible to burn entities in any dimension when they stepped on netherrack or nether quartz ore? The thought behind this is that it would be nice to make the lower level of roguelike dungeons even harder.

**Comment by SoraZodia** [comment]
Sounds nice, I would likely have to add an config option to let them specify which dimensions they would like to have it active on

**Comment by SoraZodia** [comment]
v5.1.2 should have that feature in. There is a extra config option called burn dimension list that lets you add the dimension ids that the netherrack/quartz will be able to burn the entities in.
