### ISSUE TITLE
[Suggestion] A config option to disable chain mail recipe

### ISSUE THREAD

**Issue by DWX12** [SoraZodia/Survival-Tweaks#22]
Might be times when pack makers want to use a certain recipe or disable the creation of chain mail. Sure people can use mods like CraftTweaker to remove recipes, but I'd much rather go through the official mod to remove and change stuff.

Thank you for your time and effort you put into creating this mod, it is appreciated.

**Comment by SoraZodia** [comment]
v5.2.0 should have that option now, you can find it in the mod's config file or in-game gui, it will require MC to restart for the changes to apply though
