### ISSUE TITLE
Tools Block Place 

### ISSUE THREAD

**Issue by Meskino** [SoraZodia/Survival-Tweaks#26]
I've been playing with survivaltweaks lately and I've realized that I can't place torches on the walls when I enable Tools Block Place option in the configuration.
It happens to work but in a very different way and it's shifting and placing the torch on the wall replacing it and its broke.

I hope it has a solution because that option is so broken.

**Comment by SoraZodia** [comment]
Should be fixed now in v5.2.1, let me know if there's any issues
