### ISSUE TITLE
Rightclick block place bypasses blockplace event

### ISSUE THREAD

**Issue by dries007** [SoraZodia/Survival-Tweaks#3]
Your rightclick to place block mechanic bypasses the blockplace & interact events.
You may want to try to invoke the event yourself, or you could fake a right click like [TorchTools](https://github.com/DoubleDoorDevelopment/TorchTools/blob/master/src/main/java/net/doubledoordev/torchtools/TorchTools.java#L94-L128).

**Comment by SoraZodia** [comment]
The mechanic should be able to invoke the two events now.
