### ISSUE TITLE
Bug: water bucket

### ISSUE THREAD

**Issue by VincentVan91** [SoraZodia/Survival-Tweaks#5]
I can't fill cauldron using water bucket. If i disable your mod i can fill it.

ps. In creative this bug doesn't occur.

**Comment by SoraZodia** [comment]
I'll take a look at it, thanks for letting me know.

**Comment by SoraZodia** [comment]
I can't seem to recreate it, the cauldron fills up with water on my side. Are you running any other mods other than this one?

**Comment by VincentVan91** [comment]
No, bug occurs with only survival tweaks mod active. Forge version is 1614. I recreate bug in this way: create new world in creative and take water bucket and cauldron, then i change in survival and place cauldron on the ground. In the end i try to fill it but i can't and i receive a empty bucket. If i try one more time, cauldron fills.

**Comment by SoraZodia** [comment]
Recreated it, I'll see what I can do.

**Comment by VincentVan91** [comment]
Ok, thank you

**Comment by SoraZodia** [comment]
It should be fixed now, let me know if it's still happening.

**Comment by VincentVan91** [comment]
Perfect, now it works. you are great!!
