### ISSUE TITLE
[Bug]Rightclick block Frozen : StackOverflowError

### ISSUE THREAD

**Issue by zzzqh** [SoraZodia/Survival-Tweaks#6]
Get this [log](http://pastebin.com/pLTMhAtXl) when rightclick block with tool, and game frozen.Did not happen in 1.2.0

forge version:1558
mod version:1.2.1 and 1.2.2

**Comment by SoraZodia** [comment]
Should be fixed now. Invoking a InteractEvent in a InteractEvent was a bad idea >_>

**Comment by zzzqh** [comment]
Oh,it works well! thanks.
