### ISSUE TITLE
Tool Placing with Flint and Steel (1.7.10)

### ISSUE THREAD

**Issue by DarianLStephens** [SoraZodia/Survival-Tweaks#8]
I'm not sure if some blacklisting broke or something (Speaking of blacklists, it'd be nice to have one for this in the config), but Flint and Steels are practically useless if you've got a block in your hotbar.
I got a nasty shock when I went to light my Nether Portal, yessiree.
I thought that block of obsidian was some kind of test feature left in by another mod, so I removed it and tried again (Don't ask me why). Then I hopped into a creative world to test it.
I tried again to light a nether portal, and the same problem occurred. I then tried the skyblock method of burning wood into the portal, but foolishly tried to use the Flint and Steel again, mostly out of habit.
This time, however, a block of wood was placed. I had an epiphany then, and removed the wood from my hotbar. The Flint and Steel placed obsidian. I removed the obsidian, and the fire sprung forth in all its pixel-y glory!
I then placed the obsidian back into my hotbar and switched to survival mode, and the obsidian began counting down with every use of the Flint and Steel. It was then that I realized which mod was causing the issue, and I created a new instance with just that mod to confirm it.
That leads us to now.
Instead of internally blacklisting Flint and Steel, I propose that you have a section of the config to blacklist any tool you want from placing blocks, thereby solving any issue with any other mod-added tool past, future, or present.

**Comment by SoraZodia** [comment]
I known about this for a while, but I didn't think much of it until now. I'll add an whitelist/blacklist feature in the next update.

**Comment by SoraZodia** [comment]
Took longer than it really should have, but the 1.7.10 version of the mod has that option now.
